---
- name: Create in-memory inventory from OpenStack
  hosts: localhost
  connection: local
  gather_facts: False
  become: False

  tasks:
    - name: Gather instance info
      os_server_facts:
        cloud: openstack
        region_name: regionOne
      register: __openstack_instances

    - name: Add each gathered instance as host
      add_host:
        name: "{{ item.public_v4 }}"
        group:
          - "{{ item.metadata.group }}"
          - "{{ item.metadata.deployment_name }}"
      loop: "{{ __openstack_instances.ansible_facts.openstack_servers }}"

- name: Test the in-memory inventory
  hosts: all:!localhost
  gather_facts: False

  tasks:
    - name: Show groups
      debug:
        var: groups

    - name: Wait on instances for connectivity
      wait_for_connection:

- name: Gather database facts
  hosts: database_servers
  gather_facts: true
  tasks: []

...
